-- Bestiário Cultural — Supabase
-- Execute este arquivo inteiro no SQL Editor do seu projeto Supabase.

create table if not exists public."culturalChapters" (
  id bigint generated by default as identity primary key,
  "chapterNumber" integer not null unique,
  slug varchar(96) not null unique,
  title varchar(160) not null,
  subtitle varchar(220) not null default '',
  category varchar(30) not null check (category in ('musica','danca','artesanato','festa')),
  territory text not null,
  "territorialNote" text not null,
  excerpt text not null,
  content text not null,
  "illustrationLabel" varchar(200) not null,
  "photoUrl" text not null default '',
  "photoCredit" varchar(300) not null default '',
  "photoSourceUrl" text not null default '',
  "photoLicense" varchar(200) not null default '',
  "isPublished" boolean not null default true,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public."culturalSources" (
  id bigint generated by default as identity primary key,
  "chapterSlug" varchar(96) not null references public."culturalChapters"(slug) on update cascade on delete cascade,
  title text not null,
  institution varchar(200) not null,
  "sourceUrl" text not null,
  note text not null,
  "createdAt" timestamptz not null default now()
);

create table if not exists public."culturalExtraPages" (
  id bigint generated by default as identity primary key,
  "chapterSlug" varchar(96) not null references public."culturalChapters"(slug) on update cascade on delete cascade,
  "sortOrder" integer not null default 0,
  eyebrow varchar(120) not null default 'Aprofundamento',
  title varchar(220) not null,
  content text not null,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public."culturalExtraPageImages" (
  id bigint generated by default as identity primary key,
  "pageId" bigint not null references public."culturalExtraPages"(id) on delete cascade,
  "sortOrder" integer not null default 0,
  "imageUrl" text not null,
  "altText" varchar(500) not null default '',
  credit varchar(300) not null,
  "sourceUrl" text not null,
  license varchar(200) not null,
  "createdAt" timestamptz not null default now()
);

create index if not exists cultural_sources_slug_idx on public."culturalSources" ("chapterSlug");
create index if not exists cultural_pages_slug_idx on public."culturalExtraPages" ("chapterSlug");
create index if not exists cultural_page_images_page_idx on public."culturalExtraPageImages" ("pageId");

-- Público: somente culturas publicadas.
alter table public."culturalChapters" enable row level security;
alter table public."culturalSources" enable row level security;
alter table public."culturalExtraPages" enable row level security;
alter table public."culturalExtraPageImages" enable row level security;

drop policy if exists "public_read_published_cultures" on public."culturalChapters";
create policy "public_read_published_cultures"
on public."culturalChapters" for select to anon, authenticated
using ("isPublished" = true);

drop policy if exists "public_read_sources" on public."culturalSources";
create policy "public_read_sources"
on public."culturalSources" for select to anon, authenticated
using (
  exists (
    select 1 from public."culturalChapters" c
    where c.slug = "culturalSources"."chapterSlug" and c."isPublished" = true
  )
);

drop policy if exists "public_read_pages" on public."culturalExtraPages";
create policy "public_read_pages"
on public."culturalExtraPages" for select to anon, authenticated
using (
  exists (
    select 1 from public."culturalChapters" c
    where c.slug = "culturalExtraPages"."chapterSlug" and c."isPublished" = true
  )
);

drop policy if exists "public_read_page_images" on public."culturalExtraPageImages";
create policy "public_read_page_images"
on public."culturalExtraPageImages" for select to anon, authenticated
using (
  exists (
    select 1
    from public."culturalExtraPages" p
    join public."culturalChapters" c on c.slug = p."chapterSlug"
    where p.id = "culturalExtraPageImages"."pageId" and c."isPublished" = true
  )
);

-- Storage público para as imagens do acervo.
insert into storage.buckets (id, name, public)
values ('cultural-images', 'cultural-images', true)
on conflict (id) do update set public = true;

drop policy if exists "public_read_cultural_images" on storage.objects;
create policy "public_read_cultural_images"
on storage.objects for select to anon, authenticated
using (bucket_id = 'cultural-images');

-- Uploads administrativos são feitos pelo servidor com a secret key.
-- A secret key/service_role nunca deve ser colocada no frontend.
