import type { CulturalEntry, CulturalExtraPage } from "./culturalData";
import { photoLedger } from "./photoLedger";

const commons = (file: string) => `https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(file)}`;
const source = (title: string, institution: string, url: string, note: string) => ({ title, institution, url, note });

const imageMap: Record<string, { url: string; credit: string; sourceUrl: string; license: string }> = {
  capoeira: { url: commons("Capoeira.jpg"), credit: "Bruno Rocksan · Wikimedia Commons", sourceUrl: "https://commons.wikimedia.org/wiki/File:Capoeira.jpg", license: "CC BY-SA" },
  frevo: { url: commons("Frevo.jpg"), credit: "Pedro Nurmi · Wikimedia Commons", sourceUrl: "https://commons.wikimedia.org/wiki/File:Frevo.jpg", license: "CC BY 2.0" },
  "samba-de-roda": { url: commons("Samba de Roda.jpg"), credit: "CAMBRISA · Wikimedia Commons", sourceUrl: "https://commons.wikimedia.org/wiki/File:Samba_de_Roda.jpg", license: "CC BY-SA 4.0" },
  jongo: { url: commons("Jongo de Noinha Núcleo de Artes e Cultura Campos dos Goytacazes2.jpg"), credit: "Rafael Deminicis · Wikimedia Commons", sourceUrl: "https://commons.wikimedia.org/wiki/File:Jongo_de_Noinha_N%C3%BAcleo_de_Artes_e_Cultura_Campos_dos_Goytacazes2.jpg", license: "Licença indicada na página da obra" },
  "tambor-de-crioula": { url: commons("Tambor de crioula.jpg"), credit: "Weber Ferreira Santana · Wikimedia Commons", sourceUrl: "https://commons.wikimedia.org/wiki/File:Tambor_de_crioula.jpg", license: "Licença indicada na página da obra" },
  carimbo: { url: commons("Carimbó.jpg"), credit: "Wikimedia Commons", sourceUrl: "https://commons.wikimedia.org/wiki/File:Carimb%C3%B3.jpg", license: "Ver licença da obra" },
  marabaixo: { url: commons("Marabaixo.jpg"), credit: "Ministério da Cultura · Wikimedia Commons", sourceUrl: "https://commons.wikimedia.org/wiki/File:Marabaixo.jpg", license: "CC BY 2.0" },
  "cirio-de-nazare": { url: commons("Círio de Nazaré 2014.jpg"), credit: "Wikimedia Commons", sourceUrl: "https://commons.wikimedia.org/wiki/File:C%C3%ADrio_de_Nazar%C3%A9_2014.jpg", license: "Ver licença da obra" },
  congada: { url: commons("Congada 001.jpg"), credit: "Márcia Cristina Machado · Wikimedia Commons", sourceUrl: "https://commons.wikimedia.org/wiki/File:Congada_001.jpg", license: "Licença indicada na página da obra" },
  cavalhadas: { url: commons("Cavalhadinhas em Pirenópolis, Goiás, Brasil.jpg"), credit: "Wikimedia Commons", sourceUrl: "https://commons.wikimedia.org/wiki/File:Cavalhadinhas_em_Piren%C3%B3polis%2C_Goi%C3%A1s%2C_Brasil.jpg", license: "Licença indicada na página da obra" },
  "siriri-cururu": { url: commons("Siriri e Cururu - Grupo Siriri Elétrico 01.jpg"), credit: "Wikimedia Commons", sourceUrl: "https://commons.wikimedia.org/wiki/File:Siriri_e_Cururu_-_Grupo_Siriri_El%C3%A9trico_01.jpg", license: "Licença indicada na página da obra" },
  "boi-de-mamao": { url: commons("O boi de mamao.jpg"), credit: "Wikimedia Commons", sourceUrl: "https://commons.wikimedia.org/wiki/File:O_boi_de_mamao.jpg", license: "Licença indicada na página da obra" },
};

const newEntries: CulturalEntry[] = [
  {
    number: 21, slug: "capoeira", title: "Capoeira", category: "danca", categoryLabel: "Dança", region: "Brasil; com fortes matrizes históricas na Bahia, Pernambuco e Rio de Janeiro", territorialNote: "Prática afro-brasileira que articula jogo corporal, música, roda, memória e transmissão comunitária.", subtitle: "Jogo, corpo, música e ancestralidade.", excerpt: "Manifestação afro-brasileira reconhecida como patrimônio cultural imaterial, formada por diferentes escolas, linhagens e modos de ensinar.",
    story: ["A capoeira se formou no contexto da diáspora africana no Brasil, em meio à escravidão, às estratégias de sociabilidade e às formas de resistência criadas por populações negras. Ao longo dos séculos XIX e XX, ganhou diferentes nomes, estilos e circuitos urbanos, mantendo a roda como espaço de aprendizagem, musicalidade, jogo e construção de pertencimento.", "No século XX, a sistematização de mestres como Bimba e Pastinha marcou duas linhagens de grande influência. A Capoeira Regional de Mestre Bimba valorizou uma metodologia de ensino estruturada, enquanto a tradição associada a Mestre Pastinha reforçou a continuidade da Capoeira Angola. A capoeira contemporânea reúne muitas outras linhagens e não cabe em uma única escola.", "Em 2014, a roda de capoeira e o ofício dos mestres foram reconhecidos pelo IPHAN como patrimônios culturais do Brasil, e a UNESCO havia inscrito a roda de capoeira na Lista Representativa do Patrimônio Cultural Imaterial da Humanidade em 2014. Hoje, grupos atuam em comunidades, escolas, universidades e projetos sociais no Brasil e no exterior."],
    visualMotif: "roda de capoeira, berimbau e atabaque", sources: [source("Roda de Capoeira e Ofício dos Mestres", "IPHAN", "https://bcr.iphan.gov.br/bens-culturais/roda-de-capoeira/", "Registro brasileiro da roda e do ofício dos mestres."), source("Capoeira", "UNESCO", "https://ich.unesco.org/en/RL/capoeira-circle-00892", "Reconhecimento internacional da roda de capoeira.")], photoUrl: imageMap.capoeira.url, photoCredit: imageMap.capoeira.credit, photoSourceUrl: imageMap.capoeira.sourceUrl, photoLicense: imageMap.capoeira.license,
    extraPages: []
  },
  {
    number: 22, slug: "frevo", title: "Frevo", category: "danca", categoryLabel: "Dança", region: "Recife e Olinda, Pernambuco", territorialNote: "Manifestação carnavalesca pernambucana formada por música, dança, rua, agremiações e modos de vestir.", subtitle: "Passo veloz, metais e sombrinhas.", excerpt: "O frevo transformou o carnaval de rua de Pernambuco em linguagem musical e corporal reconhecida internacionalmente.", story: ["O frevo apareceu entre o final do século XIX e as primeiras décadas do século XX, relacionado às bandas militares, bandas de música, clubes carnavalescos e disputas de rua. O termo passou a designar uma música de andamento intenso e, também, a dança que desenvolveu passos próprios a partir da movimentação dos corpos nas ruas.", "A dança do frevo, conhecida como passo, reúne movimentos acrobáticos, agachamentos, giros e deslocamentos. Sombrinhas coloridas tornaram-se um símbolo visual, mas a tradição não se resume ao adereço: ela envolve técnicas corporais, bandas, maestros, passistas, agremiações e uma extensa pedagogia carnavalesca.", "Em 2012, o Frevo foi inscrito pela UNESCO na Lista Representativa do Patrimônio Cultural Imaterial da Humanidade. O Paço do Frevo, no Recife, tornou-se importante espaço de documentação, formação e difusão da tradição."], visualMotif: "passista com sombrinha e orquestra de metais", sources: [source("Frevo", "UNESCO", "https://ich.unesco.org/en/RL/frevo-performing-arts-of-the-carnival-of-recife-00606", "Patrimônio cultural imaterial da humanidade."), source("Frevo", "Paço do Frevo", "https://www.pacodofrevo.org.br/", "Centro de referência, formação e documentação do frevo.")], photoUrl: imageMap.frevo.url, photoCredit: imageMap.frevo.credit, photoSourceUrl: imageMap.frevo.sourceUrl, photoLicense: imageMap.frevo.license, extraPages: []
  },
  {
    number: 23, slug: "samba-de-roda", title: "Samba de Roda do Recôncavo Baiano", category: "musica", categoryLabel: "Música", region: "Recôncavo da Bahia", territorialNote: "Tradição afro-brasileira ligada a comunidades do Recôncavo e a redes de mestres, sambadeiras e sambadores.", subtitle: "Roda, canto, viola e memória.", excerpt: "Uma das matrizes históricas do samba brasileiro, praticada em rodas de canto e dança no Recôncavo Baiano.", story: ["O samba de roda se consolidou no Recôncavo Baiano a partir de experiências afro-brasileiras de música, dança, religiosidade e sociabilidade. A roda organiza o espaço: participantes cantam, tocam e dançam, enquanto a comunidade responde, acompanha e participa da criação do repertório.", "Instrumentos como pandeiro, prato e faca, atabaques e viola machete aparecem em diferentes contextos. As sambadeiras ocupam papel central na continuidade da tradição, transmitindo repertórios, modos de dançar e conhecimentos sobre festas e relações comunitárias.", "Em 2005, o Samba de Roda do Recôncavo Baiano foi proclamado pela UNESCO como Obra-Prima do Patrimônio Oral e Imaterial da Humanidade e, posteriormente, inscrito na Lista Representativa. O reconhecimento reforçou ações de salvaguarda sem retirar das comunidades a responsabilidade e a autoria sobre a prática."], visualMotif: "sambadeiras em roda, pandeiro e viola machete", sources: [source("Samba de Roda do Recôncavo Baiano", "IPHAN", "https://bcr.iphan.gov.br/bens-culturais/samba-de-roda-do-reconcavo-baiano/", "Registro e documentação do patrimônio brasileiro."), source("Samba de roda of the Recôncavo of Bahia", "UNESCO", "https://ich.unesco.org/en/RL/samba-de-roda-of-the-reconcavo-of-bahia-00101", "Reconhecimento internacional." )], photoUrl: imageMap["samba-de-roda"].url, photoCredit: imageMap["samba-de-roda"].credit, photoSourceUrl: imageMap["samba-de-roda"].sourceUrl, photoLicense: imageMap["samba-de-roda"].license, extraPages: []
  },
  {
    number: 24, slug: "jongo", title: "Jongo", category: "danca", categoryLabel: "Dança", region: "Sudeste, especialmente Rio de Janeiro, São Paulo e Minas Gerais", territorialNote: "Manifestação afro-brasileira de comunidades negras, marcada por tambores, canto, dança e ancestralidade.", subtitle: "Tambor, palavra e ancestralidade.", excerpt: "Prática de matriz africana transmitida por comunidades do Sudeste e ligada à memória do trabalho, da resistência e da vida comunitária.", story: ["O jongo se desenvolveu entre populações negras do Sudeste, especialmente em comunidades formadas no entorno de antigas fazendas de café e áreas de migração de trabalhadores. Seus tambores, cantos e danças criaram espaços de encontro e preservação de referências africanas em condições históricas marcadas pela escravidão e pelo racismo.", "A roda é conduzida por tambores e cantos responsoriais. Pontos de jongo podem trabalhar metáforas, enigmas e referências comunitárias, exigindo experiência para compreender seus sentidos. A transmissão tradicional é inseparável da convivência e do respeito às pessoas mais velhas que guardam conhecimentos.", "O reconhecimento do Jongo no Sudeste como patrimônio cultural brasileiro levou a políticas de salvaguarda voltadas às comunidades e aos seus grupos. Hoje, mestres e mestras continuam formando novas gerações em terreiros, centros culturais, escolas e encontros comunitários."], visualMotif: "tambores de jongo em roda", sources: [source("Jongo no Sudeste", "IPHAN", "https://bcr.iphan.gov.br/bens-culturais/jongo-no-sudeste/", "Dossiê e referência de salvaguarda."), source("Jongo", "Iphan", "https://www.gov.br/iphan/pt-br", "Portal institucional do patrimônio cultural brasileiro.")], photoUrl: imageMap.jongo.url, photoCredit: imageMap.jongo.credit, photoSourceUrl: imageMap.jongo.sourceUrl, photoLicense: imageMap.jongo.license, extraPages: []
  },
  {
    number: 25, slug: "tambor-de-crioula", title: "Tambor de Crioula", category: "danca", categoryLabel: "Dança", region: "Maranhão, especialmente São Luís e comunidades do interior", territorialNote: "Manifestação afro-brasileira que articula dança circular, canto, percussão e devoção, com forte presença comunitária.", subtitle: "Tambor, roda e devoção.", excerpt: "Tradição maranhense de matriz africana, praticada por grupos e comunidades em festas, promessas e encontros.", story: ["O Tambor de Crioula é uma forma de expressão de matriz afro-brasileira desenvolvida no Maranhão. A prática reúne canto, percussão e dança circular e pode acontecer em diferentes situações sociais e religiosas, incluindo festas de São Benedito e celebrações de promessa.", "A roda se estrutura ao redor de três tambores principais, e a dança possui movimentos característicos. As chamadas punga ou umbigada variam conforme o contexto e os grupos, e as mulheres ocupam papel de destaque na dança, enquanto cantadores e tocadores sustentam o diálogo musical.", "O Tambor de Crioula do Maranhão foi reconhecido pelo IPHAN como Patrimônio Cultural do Brasil em 2007. A salvaguarda deve considerar a diversidade dos grupos, os espaços comunitários e a autonomia dos detentores da tradição."], visualMotif: "roda de tambor, saias e tambores maranhenses", sources: [source("Tambor de Crioula do Maranhão", "IPHAN", "https://bcr.iphan.gov.br/bens-culturais/tambor-de-crioula-do-maranhao/", "Registro e salvaguarda do patrimônio maranhense.")], photoUrl: imageMap["tambor-de-crioula"].url, photoCredit: imageMap["tambor-de-crioula"].credit, photoSourceUrl: imageMap["tambor-de-crioula"].sourceUrl, photoLicense: imageMap["tambor-de-crioula"].license, extraPages: []
  },
  {
    number: 26, slug: "carimbo", title: "Carimbó", category: "danca", categoryLabel: "Dança", region: "Pará, especialmente região do Salgado e litoral amazônico", territorialNote: "Manifestação musical e dançante amazônica associada a comunidades ribeirinhas, rurais e urbanas.", subtitle: "Amazônia em ritmo de curimbó.", excerpt: "O carimbó articula tambores, canto, dança em roda e repertórios formados por encontros indígenas, africanos e europeus na Amazônia paraense.", story: ["O carimbó se desenvolveu no Pará em contextos comunitários diversos, especialmente entre populações rurais, pesqueiras e ribeirinhas. A tradição recebeu contribuições indígenas e afro-brasileiras e passou por transformações urbanas e comerciais ao longo do século XX.", "O curimbó, tambor que dá nome à manifestação, organiza a base rítmica. A dança pode formar pares ou rodas, com saias e movimentos corporais que dialogam com o ambiente amazônico. Diferentes municípios preservam repertórios, instrumentos e modos de dançar próprios.", "Em 2014, o Carimbó foi reconhecido como Patrimônio Cultural do Brasil pelo IPHAN. A política de salvaguarda destaca mestres, grupos e comunidades como agentes fundamentais para a continuidade da prática."], visualMotif: "curimbós e roda de carimbó paraense", sources: [source("Carimbó", "IPHAN", "https://bcr.iphan.gov.br/bens-culturais/carimbo/", "Registro do carimbó como patrimônio cultural brasileiro."), source("Carimbó", "Governo do Pará", "https://www.pa.gov.br/", "Referência institucional territorial.")], photoUrl: imageMap.carimbo.url, photoCredit: imageMap.carimbo.credit, photoSourceUrl: imageMap.carimbo.sourceUrl, photoLicense: imageMap.carimbo.license, extraPages: []
  },
  {
    number: 27, slug: "marabaixo", title: "Marabaixo", category: "danca", categoryLabel: "Dança", region: "Amapá, especialmente Macapá e comunidades afro-amapaenses", territorialNote: "Manifestação afro-amapaense que articula tambores, dança, ladainhas, festas religiosas e memória comunitária.", subtitle: "Tambores da memória amapaense.", excerpt: "Uma tradição afro-amapaense central para a identidade de comunidades de Macapá e para os calendários de festas de santos.", story: ["O Marabaixo é uma manifestação musical, dançante e ritual de origem afro-amapaense. Sua formação está ligada às experiências históricas de comunidades negras do Amapá, incluindo deslocamentos, relações de trabalho, festas religiosas e construção de territórios comunitários.", "Os ladrões, como são chamados muitos dos cantos, comentam acontecimentos, relações e memórias. As caixas de marabaixo sustentam o ritmo e a dança se organiza em torno da roda e do deslocamento coletivo. A bebida gengibirra e os ciclos festivos aparecem em diferentes comunidades, com variações locais.", "O Marabaixo foi reconhecido como Patrimônio Cultural do Brasil em 2018. A Fundação Marabaixo e grupos comunitários têm papel importante na preservação, na transmissão para crianças e jovens e na defesa da memória afro-amapaense."], visualMotif: "caixas de marabaixo e roda afro-amapaense", sources: [source("Marabaixo", "IPHAN", "https://bcr.iphan.gov.br/bens-culturais/marabaixo/", "Referência de patrimônio cultural brasileiro."), source("Marabaixo", "Fundação Marabaixo", "https://www.amapa.ap.gov.br/", "Referência institucional do Amapá.")], photoUrl: imageMap.marabaixo.url, photoCredit: imageMap.marabaixo.credit, photoSourceUrl: imageMap.marabaixo.sourceUrl, photoLicense: imageMap.marabaixo.license, extraPages: []
  },
  {
    number: 28, slug: "cirio-de-nazare", title: "Círio de Nazaré", category: "festa", categoryLabel: "Festa", region: "Belém, Pará", territorialNote: "Grande celebração religiosa e cultural amazônica, formada por procissões, promessas, encontros familiares e práticas comunitárias.", subtitle: "Fé, cidade e memória amazônica.", excerpt: "Uma das maiores manifestações religiosas do Brasil, reunindo milhares de pessoas em Belém em torno da devoção a Nossa Senhora de Nazaré.", story: ["O Círio de Nazaré tem raízes na devoção mariana desenvolvida em Belém desde o período colonial e ganhou forma processional no século XVIII. Ao longo do tempo, a festa ampliou seus rituais, percursos e formas de participação, tornando-se elemento estruturante do calendário cultural paraense.", "A procissão principal é apenas uma parte de um conjunto maior de eventos e práticas. Traslados, romarias, arraial, brinquedos de miriti, promessas, culinária e encontros familiares criam uma paisagem cultural que envolve diferentes gerações e grupos sociais.", "O Círio de Nazaré foi reconhecido como Patrimônio Cultural Imaterial do Brasil pelo IPHAN em 2004 e incluído pela UNESCO na Lista Representativa do Patrimônio Cultural Imaterial da Humanidade em 2013. Sua continuidade depende da participação dos devotos e das instituições comunitárias e religiosas."], visualMotif: "procissão do Círio, berlinda e brinquedos de miriti", sources: [source("Círio de Nazaré", "IPHAN", "https://bcr.iphan.gov.br/bens-culturais/cirio-de-nazare/", "Registro brasileiro do Círio e seus bens associados."), source("Cultural festivities of the Círio de Nazaré", "UNESCO", "https://ich.unesco.org/en/RL/cultural-festivities-of-the-cirio-de-nazare-00602", "Reconhecimento internacional.")], photoUrl: imageMap["cirio-de-nazare"].url, photoCredit: imageMap["cirio-de-nazare"].credit, photoSourceUrl: imageMap["cirio-de-nazare"].sourceUrl, photoLicense: imageMap["cirio-de-nazare"].license, extraPages: []
  },
  {
    number: 29, slug: "congada", title: "Congada e Moçambique", category: "festa", categoryLabel: "Festa", region: "Minas Gerais, São Paulo e outras áreas do Sudeste e Centro-Oeste", territorialNote: "Conjunto de festas e guardas afro-brasileiras que articulam cortejo, música, devoção e memória de comunidades negras.", subtitle: "Guardas, coroas e memória negra.", excerpt: "Festas de irmandades e guardas que reelaboram referências africanas e católicas em diferentes comunidades brasileiras.", story: ["Congadas, reinados e moçambiques reúnem cortejos, cantos, tambores, coroas e personagens ligados a santos católicos, especialmente Nossa Senhora do Rosário e São Benedito. Suas histórias estão profundamente relacionadas às experiências de comunidades negras, irmandades e formas de organização social construídas desde o período escravista.", "Cada guarda possui repertórios e hierarquias próprias. Reis, rainhas, capitães, dançantes e tocadores cumprem funções transmitidas por linhagens familiares e comunitárias. Em muitos lugares, a festa organiza o calendário anual e mobiliza roupas, instrumentos, alimentação e relações de reciprocidade.", "Não existe uma única congada brasileira. O termo reúne muitas tradições locais, e a pesquisa deve respeitar nomes, memórias e formas de organização de cada comunidade. A salvaguarda contemporânea valoriza mestres, capitães e guardas como sujeitos de patrimônio."], visualMotif: "guarda de congada com tambores e estandartes", sources: [source("Congadas e Reinados", "IPHAN", "https://www.gov.br/iphan/pt-br", "Portal institucional para patrimônio imaterial e ações de salvaguarda."), source("Congada", "Museu Afro Brasil", "https://museuafrobrasil.org.br/", "Referência para cultura afro-brasileira e memória.")], photoUrl: imageMap.congada.url, photoCredit: imageMap.congada.credit, photoSourceUrl: imageMap.congada.sourceUrl, photoLicense: imageMap.congada.license, extraPages: []
  },
  {
    number: 30, slug: "cavalhadas", title: "Cavalhadas de Pirenópolis", category: "festa", categoryLabel: "Festa", region: "Pirenópolis, Goiás", territorialNote: "Festa tradicional integrada às celebrações do Divino Espírito Santo, com cavaleiros, cortejos e encenações equestres.", subtitle: "Cavaleiros, festa e cidade histórica.", excerpt: "Tradição equestre e festiva de Pirenópolis, ligada ao ciclo do Divino e a uma longa história de organização comunitária.", story: ["As Cavalhadas de Pirenópolis integram as festas do Divino Espírito Santo e apresentam uma encenação equestre inspirada em narrativas de combates entre cristãos e mouros. A tradição chegou ao Brasil em diferentes regiões e assumiu formas locais; em Pirenópolis, tornou-se um dos elementos mais conhecidos da identidade festiva da cidade.", "Os cavaleiros usam trajes, máscaras e adereços próprios, enquanto ensaios e preparativos envolvem famílias, grupos e a comunidade. As Cavalhadinhas, versão infantil, ajudam a transmitir conhecimentos e códigos da festa para novas gerações.", "A tradição deve ser compreendida em seu contexto histórico e comunitário, sem confundir a encenação festiva com documentação literal de acontecimentos medievais. O valor cultural está na continuidade, na organização social e na maneira como a comunidade recria o ritual no presente."], visualMotif: "cavaleiros mascarados em arena de Pirenópolis", sources: [source("Cavalhadas de Pirenópolis", "IPHAN", "https://bcr.iphan.gov.br/bens-culturais/cavalhadas-de-pirenopolis/", "Referência patrimonial para a festa de Pirenópolis."), source("Festa do Divino Espírito Santo", "Prefeitura de Pirenópolis", "https://pirenopolis.go.gov.br/", "Contexto territorial e calendário festivo.")], photoUrl: imageMap.cavalhadas.url, photoCredit: imageMap.cavalhadas.credit, photoSourceUrl: imageMap.cavalhadas.sourceUrl, photoLicense: imageMap.cavalhadas.license, extraPages: []
  },

];

const detailMeta: Record<string, { masters: string; groups: string; context: string; continuation: string }> = {
  "bumba-meu-boi": { masters: "Mestres e grupos variam por sotaque e comunidade. No Maranhão, nomes como Humberto de Maracanã e Apolônio Melônio tornaram-se referências de trajetórias distintas, enquanto inúmeros brincantes anônimos sustentam a tradição.", groups: "Bois de matraca, zabumba, orquestra, costa de mão e outros sotaques organizam repertórios, personagens e formas de apresentação diferentes.", context: "A tradição se relaciona à formação histórica do Maranhão, à presença africana, indígena e europeia e às festas de São João.", continuation: "A salvaguarda precisa registrar sotaques e comunidades sem transformar a diversidade em um modelo único." },
  forro: { masters: "Luiz Gonzaga é uma referência decisiva na difusão nacional do baião e de outras formas do forró, mas a história do gênero também depende de sanfoneiros, cantadores, compositores, dançarinos e mestres locais.", groups: "Tradições familiares, bandas de pé-de-serra, grupos de baile e circuitos de festas juninas formam redes permanentes de transmissão.", context: "O forró se consolidou no século XX em diálogo com migrações nordestinas, rádio, indústria fonográfica, festas rurais e urbanas.", continuation: "O reconhecimento das Matrizes Tradicionais do Forró exige preservar repertórios, modos de tocar, dançar e organizar a festa." },
  "coco-de-roda": { masters: "A transmissão é comunitária e muitos mestres e mestras são conhecidos sobretudo em seus municípios. O valor está nas redes locais de memória, não apenas em nomes consagrados.", groups: "Cocos de roda, cocos de embolada e grupos contemporâneos apresentam formações diferentes conforme o território.", context: "O coco dialoga com trabalho, festas, religiosidade e experiências afro-indígenas do Nordeste.", continuation: "Registrar versos, toques e trajetórias dos grupos ajuda a evitar que a prática seja reduzida a uma coreografia de palco." },
  "quadrilha-junina": { masters: "Marcadores, coreógrafos, costureiras, músicos e presidentes de quadrilhas cumprem funções de mestria; em cada cidade, as referências podem mudar rapidamente.", groups: "Quadrilhas tradicionais, estilizadas e competitivas convivem em circuitos municipais e estaduais.", context: "A prática brasileira reelabora danças europeias em diálogo com festas rurais nordestinas, urbanização e indústria cultural.", continuation: "A continuidade depende de espaços de ensaio, financiamento, costura, formação musical e participação comunitária." },
  maracatu: { masters: "Mestres de batuque, calungueiros, rainhas, mestres de apito e lideranças religiosas preservam conhecimentos específicos em cada nação.", groups: "Maracatu Nação e Maracatu de Baque Solto são tradições distintas; grupos urbanos de outros estados também recriam linguagens de maracatu.", context: "O maracatu tem vínculos históricos com irmandades negras, cortejos, religiosidades afro-brasileiras e o carnaval pernambucano.", continuation: "A pesquisa deve distinguir matrizes pernambucanas de reinvenções feitas em outros territórios." },
  "cavalo-marinho": { masters: "Mestres de cavalo-marinho guardam repertórios de toadas, personagens, máscaras, passos e modos de organizar a brincadeira.", groups: "Brincadeiras tradicionais da Zona da Mata convivem com grupos de pesquisa, escolas e coletivos de transmissão.", context: "A prática reúne música, dança, teatro popular e personagens em um longo ciclo festivo ligado à experiência da Zona da Mata.", continuation: "Documentar a brincadeira exige registrar personagens, relações de trabalho e trajetórias dos mestres." },
  "repente-cordel": { masters: "Cantadores como Pinto do Monteiro e Lourival Batista são referências históricas do repente; cordelistas e violeiros de diferentes gerações ampliaram a tradição.", groups: "Duplas de cantadores, festivais de viola, feiras, folheteiros e círculos de leitura formam redes de transmissão.", context: "A cantoria nordestina se relaciona à oralidade, ao trabalho rural, às feiras e à circulação de notícias e narrativas.", continuation: "A preservação deve considerar tanto o improviso oral quanto os acervos impressos e digitais." },
  "carnaval-de-rua": { masters: "Maestros, compositores, líderes de blocos e brincantes funcionam como referências locais; a memória é muitas vezes coletiva.", groups: "Blocos, orquestras de frevo, agremiações e coletivos independentes formam circuitos variados de carnaval de rua.", context: "O carnaval de rua brasileiro cresceu por associações, clubes, bairros e ocupações do espaço público, com forte participação popular.", continuation: "Mapear grupos e repertórios ajuda a reconhecer o trabalho cultural que ocorre fora dos grandes palcos." },
  fandango: { masters: "Mestres fandangueiros e construtores de instrumentos preservam repertórios, passos, afinações e modos de tocar próprios de comunidades caiçaras.", groups: "Batidas, marcas e grupos variam entre comunidades do litoral de São Paulo, Paraná e Santa Catarina.", context: "O fandango caiçara está ligado a mutirões, festas e sociabilidade de comunidades costeiras.", continuation: "A transmissão depende de espaços comunitários, instrumentos e valorização das pessoas mais velhas." },
  ciranda: { masters: "Mestres e mestras de ciranda conduzem rodas, cantos e repertórios; em Pernambuco, Lia de Itamaracá é uma referência nacional da tradição.", groups: "Grupos comunitários, rodas de praia, coletivos culturais e projetos educativos recriam a ciranda em diferentes lugares.", context: "A ciranda se desenvolveu em ambientes litorâneos e populares, sendo transformada em símbolo cultural de Pernambuco e do Nordeste.", continuation: "É importante reconhecer diferenças entre cirandas tradicionais e versões cênicas contemporâneas." },
  pastoril: { masters: "Mestras, pastoras, músicos e organizadores guardam repertórios e personagens do ciclo natalino.", groups: "Pastoris tradicionais e pastoris profanos apresentam formas e contextos distintos, especialmente em Pernambuco e Paraíba.", context: "A tradição deriva de representações do ciclo natalino e foi recriada no Nordeste em festas, palcos e comunidades.", continuation: "O registro deve preservar repertório, figurinos, personagens e histórias locais." },
  reisado: { masters: "Mestres de reisado conduzem cantos, personagens e calendários festivos; a transmissão costuma ocorrer por famílias e comunidades.", groups: "Reisados, reis de congo, guerreiros e variantes regionais assumem formas diferentes em cada estado.", context: "As festas de Reis dialogam com catolicismo popular, tradições afro-brasileiras e repertórios locais.", continuation: "O nome Reisado reúne muitas tradições e não deve apagar suas diferenças territoriais." },
  baiao: { masters: "Luiz Gonzaga é a principal referência histórica de projeção nacional, ao lado de compositores e sanfoneiros como Humberto Teixeira, Zé Dantas e Dominguinhos.", groups: "Sanfoneiros, trios de forró, bandas e escolas de música mantêm o baião em repertório vivo.", context: "O baião ganhou projeção nacional no rádio a partir dos anos 1940, articulando repertórios nordestinos e indústria cultural.", continuation: "Preservar o baião significa manter repertórios, técnicas instrumentais e histórias de seus intérpretes." },
  xaxado: { masters: "O xaxado é associado à memória dos cangaceiros e, posteriormente, a mestres e grupos de Serra Talhada e outras cidades sertanejas.", groups: "Grupos de xaxado atuam em festivais, escolas, museus e circuitos turísticos do sertão.", context: "A dança foi transformada em patrimônio cênico e identitário, dialogando com memórias do cangaço.", continuation: "É necessário diferenciar memória histórica do cangaço e recriação artística contemporânea." },
  cangaco: { masters: "Lampião e Maria Bonita são figuras centrais da memória pública do cangaço, mas a documentação histórica inclui muitos outros personagens e comunidades afetadas pelo fenômeno.", groups: "Museus, grupos de pesquisa, pesquisadores locais e coletivos de memória preservam objetos, fotografias e narrativas.", context: "O cangaço ocorreu em um Nordeste marcado por desigualdade, coronelismo, conflitos fundiários, violência e redes de poder.", continuation: "A abordagem cultural deve evitar romantização e tratar a memória com contexto histórico e múltiplas perspectivas." },
  "artesanato-de-barro": { masters: "Oleiros e artesãos transmitem técnicas de preparação da argila, modelagem, secagem e queima em oficinas familiares.", groups: "Ateliês, associações, feiras e comunidades produtoras formam redes de trabalho artesanal.", context: "A cerâmica popular combina necessidades domésticas, produção comercial e formas decorativas desenvolvidas localmente.", continuation: "A valorização depende de mercado justo, formação, documentação de técnicas e preservação dos territórios produtores." },
  "renda-renascenca": { masters: "Rendeiras mais velhas exercem papel decisivo na transmissão de pontos, leitura do papelão e organização do lacê.", groups: "Associações e grupos de rendeiras do Cariri paraibano sustentam uma economia cultural baseada no trabalho manual.", context: "A renda renascença se estabeleceu no Nordeste e ganhou forte identidade territorial em municípios paraibanos.", continuation: "A salvaguarda deve reconhecer o trabalho das rendeiras e evitar apropriação sem crédito e remuneração." },
  "ceramica-de-caruaru": { masters: "Mestre Vitalino é referência fundamental da cerâmica figurativa de Caruaru, mas sua tradição envolve muitas famílias e ceramistas posteriores.", groups: "Artesãos do Alto do Moura e outros polos produzem peças utilitárias e figurativas.", context: "A cerâmica de Caruaru se relaciona a mercados populares, feiras e representação de cenas do cotidiano nordestino.", continuation: "A pesquisa deve preservar técnicas, histórias familiares e autoria individual das peças." },
  lapinha: { masters: "Pastoras, mestras e organizadores do ciclo de Reis guardam personagens, músicas e sequências de apresentação.", groups: "Cordões e grupos de Lapinha variam por município e podem dialogar com outras formas de pastoril.", context: "A Lapinha integra tradições natalinas e do ciclo de Reis, com forte presença histórica na Paraíba.", continuation: "Registrar as versões locais evita tratar a Lapinha como um espetáculo uniforme." },
  "festa-de-sao-joao": { masters: "Organizadores comunitários, músicos, cozinheiras, artesãos e grupos de quadrilha são agentes centrais do São João.", groups: "Arraiais de bairro, quadrilhas, bandas, trios de forró e grandes festas municipais compõem o calendário.", context: "As festas juninas brasileiras combinam calendários católicos, tradições rurais, música nordestina e transformações urbanas.", continuation: "A preservação deve incluir saberes culinários, música, dança, decoração e formas de convivência." },
  capoeira: { masters: "Mestre Bimba e Mestre Pastinha são referências históricas de grande alcance, associadas respectivamente à Capoeira Regional e à tradição da Capoeira Angola. A transmissão também depende de mestres e mestras de linhagens locais, que ensinam jogo, cantos, instrumentos, ética da roda e história da comunidade.", groups: "Academias, grupos de rua, associações culturais, projetos educativos e linhagens de capoeira formam uma rede nacional e internacional. A roda de capoeira e o ofício dos mestres foram reconhecidos pelo IPHAN, e a roda foi inscrita pela UNESCO como patrimônio imaterial.", context: "A capoeira se desenvolveu no Brasil a partir das experiências de populações africanas e afro-brasileiras durante e depois da escravidão, atravessando perseguição, criminalização, reorganização comunitária e institucionalização no século XX.", continuation: "A salvaguarda deve priorizar os detentores, a transmissão oral e corporal, os instrumentos, os territórios e a memória das linhagens, sem transformar a diversidade da capoeira em um único modelo." },
  frevo: { masters: "Maestros, compositores e passistas construíram a tradição; nomes históricos como Nelson Ferreira e Capiba ajudam a compreender a formação musical do frevo. Hoje, mestres de dança, músicos e agremiações mantêm repertórios e técnicas em circulação.", groups: "Clubes carnavalescos, blocos, troças, orquestras, escolas de frevo e centros de referência como o Paço do Frevo participam da transmissão e documentação.", context: "O frevo surgiu entre o final do século XIX e o início do XX no Recife, em meio ao crescimento urbano, às bandas musicais, às agremiações carnavalescas e às disputas pelo espaço público.", continuation: "Preservar o frevo envolve música e passo, mas também agremiações, figurinos, instrumentos, mestres, espaços de ensaio e memória das ruas." },
  "samba-de-roda": { masters: "Sambadeiras, sambadores, tocadores e mestras de comunidades do Recôncavo são os principais detentores. A tradição não depende de uma única figura nacional: a mestria é distribuída entre famílias, comunidades e grupos de transmissão.", groups: "Rodas comunitárias, grupos de sambadeiras, associações culturais e mestres de viola machete mantêm diferentes repertórios, instrumentos e modos de dançar.", context: "O samba de roda se consolidou no Recôncavo Baiano em contextos afro-brasileiros de trabalho, religiosidade, festa e sociabilidade, tornando-se uma das matrizes históricas do samba brasileiro.", continuation: "A salvaguarda deve garantir protagonismo às comunidades, documentação dos repertórios e reconhecimento do trabalho das sambadeiras e sambadores." },
  jongo: { masters: "Mestres jongueiros e jongueiras preservam pontos, toques, danças, histórias familiares e conhecimentos sobre ancestralidade. A transmissão costuma acontecer por convivência e participação em rodas.", groups: "Comunidades jongueiras de estados como Rio de Janeiro, São Paulo e Minas Gerais articulam rodas, associações, grupos culturais e ações educativas.", context: "O jongo se relaciona à experiência de comunidades negras do Sudeste, especialmente em regiões marcadas pelo trabalho nas fazendas de café e por deslocamentos de populações após a escravidão.", continuation: "A continuidade exige proteger os espaços comunitários, os tambores, os repertórios de pontos e o direito das comunidades de decidir como seus conhecimentos serão registrados." },
  "tambor-de-crioula": { masters: "Mestres de tambor, coreiras e organizadores de terreiros e comunidades sustentam a transmissão. A mestria é ligada à experiência prática, ao repertório e ao conhecimento ritual e comunitário.", groups: "Grupos de tambor de crioula atuam em terreiros, festas, comunidades e circuitos culturais do Maranhão, com diferentes sotaques e modos de organização.", context: "A manifestação se desenvolveu entre comunidades negras do Maranhão e combina percussão, canto, dança, devoção e sociabilidade, mantendo relações históricas com festas religiosas e tradições afro-brasileiras.", continuation: "A salvaguarda deve respeitar os sentidos religiosos e comunitários da prática, valorizando os detentores e evitando reduzir o tambor a apresentação folclórica." },
  carimbo: { masters: "Mestres e mestras de carimbó, tocadores de curimbó, cantadores e dançantes são responsáveis por repertórios e técnicas transmitidos em comunidades do Pará.", groups: "Grupos de carimbó de diferentes municípios paraenses preservam sotaques, instrumentos, roupas, cantos e formas de dança próprias de seus territórios.", context: "O carimbó se formou na região amazônica paraense em diálogo com experiências indígenas, africanas e europeias, tornando-se uma expressão central da sociabilidade musical do estado.", continuation: "É importante reconhecer a diversidade regional e a autoria dos grupos, apoiando mestres, instrumentos, festas e espaços comunitários de transmissão." },
  marabaixo: { masters: "Mestres, ladrões de marabaixo, tocadores de caixa e comunidades negras do Amapá preservam cantos, toques, danças e memórias associadas ao ciclo do marabaixo.", groups: "Comunidades e famílias de Macapá e de outras localidades do Amapá organizam rodas, festas, encontros e ações de transmissão intergeracional.", context: "O marabaixo está profundamente ligado à história das comunidades negras do Amapá, a deslocamentos, festas religiosas e processos de afirmação de memória e pertencimento.", continuation: "A salvaguarda deve fortalecer os grupos detentores, os espaços de festa, os instrumentos e o conhecimento sobre os significados históricos dos ladrões e toques." },
  "cirio-de-nazare": { masters: "A organização envolve irmandades, promesseiros, devotos, carregadores, artesãos e agentes comunitários. Não há um único mestre: a tradição é sustentada por uma rede de saberes religiosos e festivos.", groups: "Irmandades, paróquias, associações, comunidades de devotos e trabalhadores ligados ao Círio participam de diferentes momentos do ciclo festivo em Belém e no Pará.", context: "O Círio de Nazaré se consolidou em Belém a partir do século XVIII e tornou-se uma das maiores manifestações religiosas e culturais do Brasil, articulando devoção, cortejos, promessas, música, culinária e sociabilidade.", continuation: "Documentar o Círio requer observar o ciclo inteiro e suas comunidades, evitando reduzir a manifestação apenas à grande procissão." },
  congada: { masters: "Mestres de congado, capitães de guardas, reis e rainhas, capitães de moçambique e tocadores exercem funções de liderança e transmissão conforme cada comunidade.", groups: "Congados, moçambiques, marujos, catopês e outras guardas assumem nomes e repertórios diferentes em Minas Gerais, Goiás, São Paulo e outros estados.", context: "As congadas articulam referências afro-brasileiras, catolicismo popular, memória de reinos simbólicos e experiências comunitárias, com trajetórias diferentes conforme o território.", continuation: "A salvaguarda deve respeitar a dimensão religiosa, as hierarquias internas e as especificidades de cada guarda, evitando homogeneizar a tradição." },
  cavalhadas: { masters: "Cavaleiros experientes, organizadores, artesãos de adereços e famílias que participam do ciclo festivo preservam técnicas, personagens e repertórios. Em Pirenópolis, a tradição possui forte continuidade comunitária.", groups: "Cavalhadas, mascarados, cavaleiros, bandas, festeiros e comunidades religiosas integram o ciclo das festas do Divino em diferentes regiões.", context: "As cavalhadas brasileiras foram recriadas em contextos de festas religiosas e comunitárias, assumindo características locais. Em Pirenópolis, Goiás, a encenação se consolidou como uma importante tradição do ciclo do Divino.", continuation: "A preservação deve incluir preparação dos cavalos, confecção de trajes, música, personagens, organização comunitária e memória dos participantes." },
};

function pagesFor(entry: CulturalEntry, meta: { masters: string; groups: string; context: string; continuation: string }, image: { url: string; credit: string; sourceUrl: string; license: string }): CulturalExtraPage[] {
  const mkImages = (label: string) => [0, 1].map((i) => ({ imageUrl: image.url, altText: `${label}: registro fotográfico de ${entry.title}`, credit: image.credit, sourceUrl: image.sourceUrl, license: image.license }));
  return [
    { eyebrow: "Aprofundamento · 01", title: "Contexto histórico", content: `${meta.context}\n\nA história de ${entry.title} não pode ser separada das pessoas que a praticam. Mudanças econômicas, urbanização, políticas culturais, migrações e meios de comunicação alteraram a forma de circulação da tradição, mas não eliminaram sua capacidade de se reinventar.`, images: mkImages("Contexto histórico") },
    { eyebrow: "Aprofundamento · 02", title: "Mestres, mestras e grupos", content: `${meta.masters}\n\n${meta.groups}\n\nQuando não há uma lista estável de mestres reconhecidos, o Bestiário prioriza a ideia de mestria comunitária: saberes podem estar distribuídos entre músicos, dançantes, artesãos, organizadores, anciãos e famílias.`, images: mkImages("Mestres e grupos") },
    { eyebrow: "Aprofundamento · 03", title: "Continuidade e salvaguarda", content: `${meta.continuation}\n\nPreservar não significa congelar uma manifestação. Significa criar condições para que seus detentores possam continuar ensinando, praticando, transformando e decidindo como suas histórias serão apresentadas.`, images: mkImages("Salvaguarda") },
  ];
}

export function applyCulturalExpansion(entries: CulturalEntry[]): CulturalEntry[] {
  const all = [...entries, ...newEntries];
  return all.map((entry, index) => {
    const image = imageMap[entry.slug] ?? (entry.photoUrl ? { url: entry.photoUrl, credit: entry.photoCredit || "Acervo Bestiário Cultural", sourceUrl: entry.photoSourceUrl || entry.photoUrl, license: entry.photoLicense || "Ver fonte original" } : photoLedger[entry.slug] ? { url: photoLedger[entry.slug].image, credit: photoLedger[entry.slug].label, sourceUrl: photoLedger[entry.slug].url, license: "Ver licença na fonte" } : undefined);
    const meta = detailMeta[entry.slug];
    const deepPages = image && meta ? pagesFor(entry, meta, image) : entry.extraPages ?? [];
    return {
      ...entry,
      number: index + 1,
      extraPages: deepPages.length ? deepPages : entry.extraPages ?? [],
      isPublished: true,
    };
  });
}
