export type EditorialNote = {
  heading: string;
  fieldNote: string;
  invitation: string;
};

export const editorialNotes: Record<string, EditorialNote> = {
  "bumba-meu-boi": { heading: "Quando o boi entra em cena", fieldNote: "Antes de ser capítulo, o boi é encontro: gente reunida em torno de uma figura que dança, provoca riso e abre espaço para a música. A fotografia não substitui a brincadeira, mas guarda um instante de sua energia coletiva.", invitation: "Repare nos bordados, nos olhos do boi e na distância curta entre quem brinca e quem assiste." },
  forro: { heading: "O salão como conversa", fieldNote: "No forró, o corpo aprende a escutar. Há uma negociação delicada entre o fole, o passo e a proximidade de quem dança. Mais do que uma trilha sonora, ele cria uma maneira de ocupar o salão sem pressa.", invitation: "Imagine a sanfona chamando e o casal encontrando o próprio compasso." },
  "coco-de-roda": { heading: "O chão responde", fieldNote: "O coco pede roda, palma e escuta. Sua força não está em uma coreografia isolada, mas na resposta que cada pessoa oferece ao canto e ao chão. A presença coletiva é parte da música.", invitation: "Olhe para os pés e para as mãos: ali o ritmo também se escreve." },
  "quadrilha-junina": { heading: "Uma cidade montada para dançar", fieldNote: "A quadrilha organiza o arraial como pequena cidade imaginada: há pares, chamadas, caminhos e reencontros. Entre o ensaio e a noite da apresentação, ela reúne figurino, memória de bairro e muito trabalho de bastidor.", invitation: "Procure os gestos de orientação entre os pares; eles contam uma história de cooperação." },
  maracatu: { heading: "Peso, brilho e cortejo", fieldNote: "No maracatu, as alfaias não chegam sozinhas. O som vem acompanhado de roupas, personagens, coroação e deslocamento pela rua. É uma presença que se reconhece antes mesmo de ser explicada.", invitation: "Observe como o cortejo transforma rua em palco e palco em território compartilhado." },
  "cavalo-marinho": { heading: "Uma noite inteira de invenção", fieldNote: "O Cavalo-Marinho vive de personagens que entram, saem, improvisam e voltam a surpreender. A brincadeira guarda camadas de música, humor e memória do trabalho nos canaviais, sempre filtradas pela criatividade de quem a conduz.", invitation: "Fique atento aos detalhes da máscara e à pausa entre uma entrada e outra." },
  "repente-cordel": { heading: "A palavra em disputa e cuidado", fieldNote: "No repente, a rima não é apenas ornamento: ela pede atenção, rapidez e respeito por quem responde. No cordel, a folha circula de mão em mão e faz da leitura uma conversa pública. Em ambos, a palavra chega com endereço.", invitation: "Leia em voz baixa e perceba onde a frase pede respiração." },
  "carnaval-de-rua": { heading: "A rua se reconhece", fieldNote: "O carnaval de rua começa muito antes do desfile: na sede do bloco, no ensaio, na conversa sobre fantasia e no combinado entre vizinhos. Quando a orquestra entra, a cidade passa a caber em outra escala.", invitation: "Procure o gesto de quem acompanha da calçada; ele também participa do cortejo." },
  fandango: { heading: "Ritmo que atravessa água e terra", fieldNote: "O fandango aparece aqui como aproximação curatorial de uma tradição que se organiza em outros territórios brasileiros. Sua presença convida a comparar instrumentos, passos e redes de transmissão sem apagar as diferenças de cada comunidade.", invitation: "Use esta página como ponte: compare o que se parece e o que não deve ser confundido." },
  ciranda: { heading: "Muitas mãos, uma roda", fieldNote: "A ciranda dispensa plateia distante. Quem chega pode entrar, aprender o passo e ajudar a manter a roda viva. A força está menos na perfeição do movimento e mais na disponibilidade de acompanhar o outro.", invitation: "Imagine a roda crescendo para acolher quem acabou de chegar." },
  pastoril: { heading: "Fitas, vozes e escolha", fieldNote: "No pastoril, cor e canto organizam uma cena de delicadeza e disputa. As personagens, os cordões e o público criam uma relação direta, às vezes brincalhona, que faz cada apresentação depender de quem está ali.", invitation: "Repare como as cores funcionam como fala antes mesmo da canção." },
  reisado: { heading: "Visita que traz memória", fieldNote: "O reisado caminha: visita casas, ocupa ruas e reúne personagens que carregam repertórios de fé, brincadeira e aprendizado oral. Cada grupo guarda maneiras próprias de cantar, vestir e contar sua chegada.", invitation: "Observe a ordem do cortejo e pense em quantas histórias cabem em uma visita." },
  baiao: { heading: "Um fole que muda o horizonte", fieldNote: "O baião tornou o Nordeste audível em muitas partes do país, mas não cabe em uma única figura. Ele vive em sanfonas, triângulos, zabumbas, bailes e releituras que continuam encontrando novas escutas.", invitation: "Escute mentalmente o diálogo entre o grave da zabumba e o desenho da sanfona." },
  xaxado: { heading: "Passo marcado, memória em movimento", fieldNote: "O xaxado traz um ritmo seco e coletivo que faz do passo uma marca visível. Hoje, grupos de dança, escolas e comunidades reelaboram essa memória, discutindo também o que significa representar o sertão no presente.", invitation: "Olhe para a linha que o grupo forma: ela fala de união, força e encenação." },
  cangaco: { heading: "Entre documento e imaginação", fieldNote: "O cangaço não é enfeite de sertão. É tema de memória, violência, desigualdade e invenção cultural. Fotografias históricas exigem cuidado: elas contam muito, mas também carregam o olhar de quem as produziu e circulou.", invitation: "Antes de admirar a indumentária, pergunte o que a imagem escolhe mostrar e o que deixa de fora." },
  "artesanato-de-barro": { heading: "A matéria guarda a marca da mão", fieldNote: "No barro, cada pressão, corte e queima deixa uma decisão visível. A peça pronta é só uma parte da história; há terra escolhida, tempo de secagem, conversa de oficina e conhecimento transmitido sem manual único.", invitation: "Aproxime o olhar das marcas da superfície: elas registram gesto e tempo." },
  "renda-renascenca": { heading: "Trama que pede demora", fieldNote: "A renda renascença faz da paciência uma linguagem. Sobre o bastidor, linhas se encontram, se afastam e voltam a formar desenho. É um trabalho que convida a desacelerar o olhar e reconhecer a inteligência da repetição.", invitation: "Siga uma linha com os olhos e veja como ela se transforma em desenho coletivo." },
  "ceramica-de-caruaru": { heading: "Barro que conta cotidiano", fieldNote: "A cerâmica de Caruaru aparece como capítulo de comparação regional. Nela, figuras, feiras e cenas ordinárias ganham volume e humor. A aproximação ajuda a perceber como o barro nordestino cria vocabulários locais muito diferentes entre si.", invitation: "Veja quais cenas cotidianas foram escolhidas para permanecer no barro." },
  lapinha: { heading: "Uma casa montada para o sagrado", fieldNote: "A lapinha transforma um canto da casa, da igreja ou da praça em lugar de visita. Não é apenas cenário: reúne objetos guardados, personagens, canções e pessoas que voltam todos os anos para renovar uma tradição.", invitation: "Repare na escala dos elementos e no cuidado com que cada figura encontra seu lugar." },
  "festa-de-sao-joao": { heading: "A cidade acende outra noite", fieldNote: "Na festa de São João, bandeirolas e fogueira são só a parte mais visível. Há cozinhas, quadrilhas, feiras, palcos e encontros familiares que transformam o calendário em experiência de cidade. Cada comunidade reconhece a festa a seu modo.", invitation: "Olhe além do palco: a festa também acontece nos pequenos encontros ao redor dele." },
};
